name: CI/CD - RELEASE
on:
    push:
        branches:
            - release
            - release/*
    pull_request:
        types: [synchronize]
    workflow_dispatch:

env:
    NODE_VERSION: 18.17.1

jobs:
    release:
        name: 'Release'
        runs-on: ubuntu-latest
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '🔧  Setup NodeJS ${{ env.NODE_VERSION }}'
              if: steps.changed-test-files.outputs.any_changed == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: '🔧 Install dependencies'
              if: steps.changed-test-files.outputs.any_changed == 'true'
              run: yarn install

            - name: '🚀 Create Release'
              run: yarn semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
