name: CI/CD - PROD
on:
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

env:
    NODE_VERSION: 18.17.1
    BASE_URL: ${{ secrets.PROD_BASE_URL }}

jobs:
    build-n-package:
        name: 'Build & Package'
        runs-on: ubuntu-latest
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '🔧  Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: '🔧 Install dependencies'
              run: yarn install

            - name: 'Run Build'
              run: yarn run build:prod

            - name: 'Package ./apps'
              run: yarn run package

            - name: 'Upload apps artifact'
              uses: actions/upload-artifact@v3
              with:
                  name: apps-${{ github.run_number }}-${{ github.run_id }}
                  path: './package/apps/'

    deploy-stage:
        name: 'Deploy to Netlify PROD env.'
        runs-on: ubuntu-latest
        needs: [build-n-package]
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Create package/dist'
              run: mkdir -p package/apps

            - uses: actions/download-artifact@v3
              with:
                  name: apps-${{ github.run_number }}-${{ github.run_id }}
                  path: package/apps

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  # Upload entire repository
                  path: './package/apps'

            - name: '🚀 Deploy to Netlify PROD env.'
              uses: nwtgck/actions-netlify@v2.0
              with:
                  publish-dir: './package/apps'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
              timeout-minutes: 1

    deploy-storybook-prod:
        name: 'Deploy Storybook to Netlify PROD env.'
        runs-on: ubuntu-latest
        needs: [vrt-chromatic]
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Create package/storybook'
              run: mkdir -p package/storybook

            - uses: actions/download-artifact@v3
              with:
                  name: storybook-${{ github.run_number }}-${{ github.run_id }}
                  path: package/storybook

            - name: '🚀 Deploy to Netlify'
              uses: nwtgck/actions-netlify@v2.0
              with:
                  publish-dir: './package/storybook'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.PROD_STORYBOOK_NETLIFY_SITE_ID }}
              timeout-minutes: 1
