name: CI/CD - RELEASE
on:
    push:
        branches:
            - release
    pull_request:
        types: [synchronize]
    workflow_dispatch:

env:
    NODE_VERSION: 18.17.1

jobs:
    release:
        name: 'Release'
        runs-on: ubuntu-latest
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: 'Release'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: echo 'Prepare and run E2E tests'
