name: CI/CD - RELEASE
on:
    push:
        branches:
            - release
    pull_request:
        types: [synchronize]
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

env:
    NODE_VERSION: 18.17.1
    BASE_URL: ${{ secrets.BASE_URL }}

jobs:
    test:
        name: 'Automated Tests'
        runs-on: ubuntu-latest

        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '游댌  Verify Changed Files [shared, backend, database, frontend]'
              uses: tj-actions/changed-files@v35
              id: changed-test-files
              with:
                  files: |
                      shared/**/*
                      backend/**/*
                      database/**/*
                      frontend/**/*

            - name: List all changed files
              run: |
                  for file in ${{ steps.changed-test-files.outputs.all_changed_files }}; do
                    echo "$file was changed"
                  done

            - name: '游댢  Setup NodeJS ${{ env.NODE_VERSION }}'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: '游댢 Install dependencies'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: yarn install

            - name: 'Run Tests'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: yarn run test

            - name: 'Upload coverage artifact'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              uses: actions/upload-artifact@v3
              with:
                  name: coverage-${{ github.run_number }}-${{ github.run_id }}
                  path: './package/coverage/'

    vrt-chromatic:
        name: 'Visual Regression Testing w. Chromatic'
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '游댌  Verify Changed Files [shared, frontend]'
              uses: tj-actions/changed-files@v35
              id: changed-test-files
              with:
                  files: |
                      shared/**/*
                      frontend/**/*

            - name: '游댢  Setup NodeJS ${{ env.NODE_VERSION }}'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: '游댢 Install dependencies'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: yarn install

            - name: '游깯 Run VRT w. Chromatic'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              env:
                  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
              run: yarn test:chromatic

    e2e-tests:
        name: 'End-to-End Tests'
        runs-on: ubuntu-latest
        needs: [test, vrt-chromatic]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: '游댌  Verify Changed Files [shared, backend, database, frontend, assets]'
              uses: tj-actions/changed-files@v35
              id: changed-test-files
              with:
                  files: |
                      shared/**/*
                      frontend/**/*
                      assets/**/*
                      backend/**/*
                      database/**/*
            - name: 'Prepare E2E Tests'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: echo 'Prepare and run E2E tests'

    deploy-test-aws:
        name: 'Deploy to AWS TEST env.'
        runs-on: ubuntu-latest
        needs: [vrt-chromatic, e2e-tests]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: '游댌  Verify Changed Files [shared, backend, database, frontend, assets]'
              uses: tj-actions/changed-files@v35
              id: changed-test-files
              with:
                  files: |
                      shared/**/*
                      frontend/**/*
                      assets/**/*
                      backend/**/*
                      database/**/*
            - name: 'Build /apps'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: echo "Build /apps - TO BE IMPLEMENTED"

    deploy-storybook-test-aws:
        name: 'Deploy Storybook to AWS TEST env.'
        runs-on: ubuntu-latest
        needs: [vrt-chromatic, e2e-tests]
        steps:
            - name: '游닌 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: '游댌  Verify Changed Files [shared, backend, database, frontend, assets]'
              uses: tj-actions/changed-files@v35
              id: changed-test-files
              with:
                  files: |
                      shared/**/*
                      frontend/**/*
                      assets/**/*
                      backend/**/*
                      database/**/*
            - name: 'Build /storybook'
              if: steps.changed-test.files.outputs.test_any_changed == 'true'
              run: echo "Build /storybook - TO BE IMPLEMENTED"
